### ISSUE TITLE
Extension todo list before PR

### ISSUE THREAD

**Issue by Blatzar** [recloudstream/cloudstream#1]
- [ ] Better local file support (remove extensions from within the app)
- [ ] A functional auto updater
- [ ] Repo management (e.g: download/delete all plugins from a repo button)
- [ ] Removal of plugins when repo is removed
- [ ] Fix bug where provider appears twice if removed and installed
- [ ] Show nsfw plugins
- [ ] A forkable repository for making plugins
- [ ] TV navigation support

**Comment by C10udburst** [comment]
Moved to a [project](https://github.com/recloudstream/cloudstream/projects)
