### ISSUE TITLE
Slow App response time along with Meta Data Issue

### ISSUE THREAD

**Issue by ItzNuggetz** [recloudstream/cloudstream#1126]
### Steps to reproduce

1. All the shows I want to watch whether be pretty old or currently airing has meta data not available mentioned and for most of the Series or a movie won't play and even if it does it takes forever to appear
2. I'm mostly on cellular networks eg. Airtel or Jio as I'm from India. The red app and blue I have tried has the same slow response time issue.
3. I tried using DNS over HTTPS to adguard and had VPN on board but none of them works as the issue remains the same.
4. Series like Panchayat and Farzi won't play a thing due to multiple bugs. 

### Expected behavior

The movies or shows should play with a good response time from the app. 
![Screenshot_20240608_232856](https://github.com/recloudstream/cloudstream/assets/166253246/f1942b43-6d0b-48b9-95d3-3a823dbabdab)
[logcat_2024_06_08_23_43.txt](https://github.com/user-attachments/files/15749248/logcat_2024_06_08_23_43.txt)

### Actual behavior

Video fails to load or links are failed to be fetched due to the meta data not available issue and even if it does it's very slow and sometimes the page for the series doesn't appear at all. 

### Cloudstream version and commit hash

4.3.2 7eec0ef

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by ItzNuggetz** [comment]
How do I do that from plug in maker and for logcat I would just try to attach the logcat file
[logcat_2024_06_09_00_22.txt](https://github.com/user-attachments/files/15749332/logcat_2024_06_09_00_22.txt)

**Comment by ItzNuggetz** [comment]
I'm sorry but it seems like logcat won't attach I am doing it from my phone HONOR 90 but the issues I mentioned like slow response time for the series or movies not to appear or they won't play altogether

**Comment by fire-light42** [comment]
This is an extension issue, and will therefore be closed.
