### ISSUE TITLE
Add Kitsu account to tracking

### ISSUE THREAD

**Issue by WEPOXS** [recloudstream/cloudstream#933]
### Describe your suggested feature

Kitsu.io

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.
